export const themeKeywords = {
  // Universal human emotions and states
  'Love': [
    // Generic (weight 1-3)
    {word: 'love', weight: 1},
    {word: 'heart', weight: 1},
    {word: 'romance', weight: 2},
    {word: 'affection', weight: 2},
    {word: 'lover', weight: 2},
    {word: 'beloved', weight: 2},
    {word: 'passion', weight: 2},
    {word: 'desire', weight: 2},
    {word: 'date', weight: 2},
    {word: 'relationship', weight: 2},
    {word: 'adore', weight: 2},
    {word: 'devotion', weight: 3},
    {word: 'fondness', weight: 3},
    {word: 'crush', weight: 2},
    {word: 'intimacy', weight: 3},
    {word: 'tenderness', weight: 3},
    {word: 'longing', weight: 3},
    {word: 'yearning', weight: 3},
    {word: 'embrace', weight: 2},
    
    // More specific contemporary (weight 4-7)
    {word: 'self-love', weight: 4},
    {word: 'heartbreak', weight: 3},
    {word: 'infatuation', weight: 4},
    {word: 'chemistry', weight: 4},
    {word: 'situationship', weight: 6},
    {word: 'feels', weight: 5},
    {word: 'vibe', weight: 5},
    {word: 'bae', weight: 6},
    {word: 'clingy', weight: 4},
    {word: 'unrequited', weight: 4},
    {word: 'talking', weight: 5},
    {word: 'honeymoon-phase', weight: 5},
    {word: 'toxic', weight: 4},
    {word: 'commitment', weight: 3},
    {word: 'authenticity', weight: 4},
    {word: 'vulnerability', weight: 4},
    {word: 'connection', weight: 3},
    {word: 'empathy', weight: 3},
    {word: 'resilience', weight: 4},
    {word: 'fling', weight: 4},
    {word: 'on-off', weight: 5},
    {word: 'love-hate', weight: 4},
    {word: 'heartache', weight: 3},
    {word: 'tight-knit', weight: 4},
    
    // Very specific/niche contemporary (weight 7-10)
    {word: 'ghosting', weight: 7},
    {word: 'lovecore', weight: 8},
    {word: 'ship', weight: 7},
    {word: 'cuffing-season', weight: 8},
    {word: 'slowburn', weight: 7},
    {word: 'cuddlecore', weight: 9},
    {word: 'breadcrumbing', weight: 8},
    {word: 'zombieing', weight: 9},
    {word: 'cushioning', weight: 8},
    {word: 'kittenfishing', weight: 9},
    {word: 'stashing', weight: 8},
    {word: 'backsliding', weight: 8},
    {word: 'benching', weight: 8},
    {word: 'dry-dating', weight: 9},
    {word: 'lovebomb', weight: 7},
    {word: 'gaslighting', weight: 6},
    {word: 'manipulative', weight: 5},
    {word: 'co-dependent', weight: 6},
    {word: 'metrosexual', weight: 8},
    {word: 'dating-app', weight: 6},
    {word: 'digital-love', weight: 7},
    {word: 'slow-dating', weight: 7},
    {word: 'orbiting', weight: 8},
    {word: 'power-dynamics', weight: 6},
    {word: 'soft-launching', weight: 9},
    {word: 'hard-launching', weight: 9},
    {word: 'rizz', weight: 8},
    {word: 'simp', weight: 7},
    {word: 'main-character-energy', weight: 8},
    
    // Historical/classical terms (weight 6-10)
    {word: 'pragma', weight: 9},
    {word: 'philia', weight: 9},
    {word: 'eros', weight: 8},
    {word: 'agape', weight: 9},
    {word: 'mania', weight: 8},
    {word: 'philautia', weight: 9},
    {word: 'storge', weight: 9},
    {word: 'courtly-love', weight: 8},
    {word: 'troubadour', weight: 9},
    {word: 'carnal-love', weight: 7},
    {word: 'platonic', weight: 6},
    {word: 'chivalry', weight: 7},
    {word: 'courtship', weight: 6}
  ],

  'Grief': [
    // Generic (1-3)
    {word: 'grief', weight: 1},
    {word: 'sorrow', weight: 1},
    {word: 'mourning', weight: 2},
    {word: 'loss', weight: 1},
    {word: 'heartache', weight: 2},
    {word: 'bereavement', weight: 3},
    {word: 'sadness', weight: 1},
    {word: 'tears', weight: 2},
    {word: 'weep', weight: 2},
    {word: 'anguish', weight: 2},
    {word: 'pain', weight: 1},
    {word: 'lament', weight: 3},
    {word: 'funeral', weight: 2},
    {word: 'cry', weight: 1},
    {word: 'regret', weight: 2},
    {word: 'memorial', weight: 2},
    {word: 'gone', weight: 2},
    {word: 'goodbye', weight: 2},
    {word: 'absence', weight: 2},
    {word: 'darkness', weight: 2},
    
    // More specific (4-7)
    {word: 'anticipatory-grief', weight: 6},
    {word: 'complicated-grief', weight: 6},
    {word: 'disenfranchised-grief', weight: 7},
    {word: 'ambiguous-loss', weight: 6},
    {word: 'grief-brain', weight: 5},
    {word: 'widow-fog', weight: 6},
    {word: 'grief-bursts', weight: 5},
    {word: 'anniversary-reaction', weight: 6},
    {word: 'continuing-bonds', weight: 5},
    {word: 'grief-work', weight: 4},
    {word: 'bereaved', weight: 3},
    {word: 'mourner', weight: 3},
    {word: 'memorial-tattoo', weight: 5},
    {word: 'grief-dreams', weight: 5},
    {word: 'phantom-grief', weight: 6},
    
    // Niche/specific (7-10)
    {word: 'kubler-ross-stages', weight: 8},
    {word: 'thanatology', weight: 9},
    {word: 'grief-counseling', weight: 6},
    {word: 'keening', weight: 8},
    {word: 'shiva', weight: 7},
    {word: 'wake', weight: 4},
    {word: 'eulogy', weight: 4},
    {word: 'obituary', weight: 4},
    {word: 'death-anniversary', weight: 5},
    {word: 'grief-support-group', weight: 6},
    {word: 'widow-brain', weight: 7},
    {word: 'grief-rituals', weight: 5},
    {word: 'memento-mori', weight: 8},
    {word: 'lachrymose', weight: 9},
    {word: 'elegiac', weight: 8},
    {word: 'threnody', weight: 9},
    {word: 'dirge', weight: 7}
  ],

  'Hope': [
    // Generic (1-3)
    {word: 'hope', weight: 1},
    {word: 'dream', weight: 1},
    {word: 'wish', weight: 1},
    {word: 'future', weight: 2},
    {word: 'tomorrow', weight: 2},
    {word: 'light', weight: 2},
    {word: 'expectation', weight: 2},
    {word: 'optimism', weight: 2},
    {word: 'faith', weight: 2},
    {word: 'anticipation', weight: 2},
    {word: 'promise', weight: 2},
    {word: 'belief', weight: 2},
    {word: 'trust', weight: 2},
    {word: 'wishful', weight: 3},
    {word: 'uplift', weight: 3},
    {word: 'sunrise', weight: 2},
    {word: 'bright', weight: 2},
    {word: 'dawn', weight: 2},
    {word: 'aspiration', weight: 3},
    {word: 'motivation', weight: 2},
    
    // More specific (4-7)
    {word: 'vision-board', weight: 5},
    {word: 'manifestation', weight: 5},
    {word: 'positive-thinking', weight: 4},
    {word: 'growth-mindset', weight: 5},
    {word: 'silver-lining', weight: 4},
    {word: 'glass-half-full', weight: 4},
    {word: 'hopeful-realism', weight: 6},
    {word: 'radical-hope', weight: 6},
    {word: 'hope-therapy', weight: 6},
    {word: 'wishful-thinking', weight: 4},
    {word: 'optimistic-bias', weight: 5},
    {word: 'future-self', weight: 5},
    {word: 'bucket-list', weight: 4},
    {word: 'dream-big', weight: 4},
    {word: 'goal-setting', weight: 4},
    
    // Niche/specific (7-10)
    {word: 'hope-theory', weight: 8},
    {word: 'learned-optimism', weight: 7},
    {word: 'post-traumatic-growth', weight: 7},
    {word: 'resilience-building', weight: 6},
    {word: 'toxic-positivity', weight: 7},
    {word: 'hopium', weight: 8},
    {word: 'sanguine', weight: 7},
    {word: 'pollyanna-syndrome', weight: 8},
    {word: 'anticipatory-joy', weight: 7},
    {word: 'esperanza', weight: 8},
    {word: 'ubuntu', weight: 9},
    {word: 'schadenfreude-opposite', weight: 9},
    {word: 'eudaimonia', weight: 9},
    {word: 'ikigai', weight: 8},
    {word: 'hygge-hope', weight: 8}
  ],

  'Despair': [
    // Generic (1-3)
    {word: 'despair', weight: 1},
    {word: 'hopeless', weight: 2},
    {word: 'lost', weight: 1},
    {word: 'depression', weight: 2},
    {word: 'darkness', weight: 2},
    {word: 'emptiness', weight: 2},
    {word: 'alone', weight: 1},
    {word: 'dark', weight: 1},
    {word: 'anguish', weight: 2},
    {word: 'helpless', weight: 2},
    {word: 'void', weight: 2},
    {word: 'misery', weight: 2},
    {word: 'tear', weight: 1},
    {word: 'crying', weight: 1},
    {word: 'sad', weight: 1},
    {word: 'melancholy', weight: 3},
    {word: 'grief', weight: 2},
    {word: 'death', weight: 2},
    {word: 'lonely', weight: 2},
    
    // More specific (4-7)
    {word: 'rock-bottom', weight: 4},
    {word: 'existential-crisis', weight: 5},
    {word: 'quarter-life-crisis', weight: 5},
    {word: 'mid-life-crisis', weight: 5},
    {word: 'burnout', weight: 4},
    {word: 'emotional-numbness', weight: 5},
    {word: 'anhedonia', weight: 6},
    {word: 'learned-helplessness', weight: 6},
    {word: 'doom-spiral', weight: 5},
    {word: 'catastrophizing', weight: 5},
    {word: 'rumination', weight: 5},
    {word: 'depression-nap', weight: 5},
    {word: 'executive-dysfunction', weight: 6},
    {word: 'emotional-exhaustion', weight: 5},
    {word: 'therapy-speak', weight: 6},
    
    // Niche/specific (7-10)
    {word: 'weltschmerz', weight: 9},
    {word: 'saudade', weight: 8},
    {word: 'mono-no-aware', weight: 9},
    {word: 'duende', weight: 9},
    {word: 'acedia', weight: 8},
    {word: 'languor', weight: 7},
    {word: 'spleen', weight: 8},
    {world: 'ennui', weight: 8},
    {word: 'taedium-vitae', weight: 9},
    {word: 'existential-dread', weight: 6},
    {word: 'nihilistic', weight: 6},
    {word: 'absurdist', weight: 7},
    {word: 'sisyphean', weight: 8},
    {word: 'kafkaesque', weight: 8}
  ],

  'Joy': [
    // Generic (1-3)
    {word: 'joy', weight: 1},
    {word: 'happiness', weight: 1},
    {word: 'smile', weight: 1},
    {word: 'laughter', weight: 1},
    {word: 'celebrate', weight: 2},
    {word: 'delight', weight: 2},
    {word: 'pleasure', weight: 2},
    {word: 'cheer', weight: 2},
    {word: 'bliss', weight: 2},
    {word: 'glee', weight: 2},
    {word: 'fun', weight: 1},
    {word: 'merry', weight: 2},
    {word: 'bright', weight: 2},
    {word: 'success', weight: 2},
    {word: 'victory', weight: 2},
    {word: 'lightness', weight: 3},
    {word: 'exuberance', weight: 3},
    {word: 'contentment', weight: 3},
    
    // More specific (4-7)
    {word: 'euphoria', weight: 4},
    {word: 'elation', weight: 4},
    {word: 'jubilation', weight: 4},
    {word: 'ecstasy', weight: 4},
    {word: 'rapture', weight: 5},
    {word: 'exhilaration', weight: 4},
    {word: 'pure-joy', weight: 4},
    {word: 'infectious-laughter', weight: 5},
    {word: 'belly-laugh', weight: 4},
    {word: 'giggle-fit', weight: 4},
    {word: 'happy-tears', weight: 4},
    {word: 'joy-ride', weight: 4},
    {word: 'high-on-life', weight: 5},
    {word: 'good-vibes', weight: 4},
    {word: 'happy-place', weight: 4},
    {word: 'sunshine-personality', weight: 5},
    
    // Niche/specific (7-10)
    {word: 'endorphin-rush', weight: 6},
    {word: 'dopamine-hit', weight: 6},
    {word: 'serotonin-boost', weight: 6},
    {word: 'runner-high', weight: 6},
    {word: 'flow-state', weight: 6},
    {word: 'mudita', weight: 9},
    {word: 'joie-de-vivre', weight: 7},
    {word: 'schadenfreude', weight: 7},
    {word: 'frisson', weight: 8},
    {word: 'eudaimonia', weight: 8},
    {word: 'beatific', weight: 8},
    {word: 'rhapsodic', weight: 8},
    {word: 'transcendent-joy', weight: 7},
    {word: 'pristine-happiness', weight: 7}
  ],

  'Loneliness': [
    // Generic (1-3)
    {word: 'lonely', weight: 1},
    {word: 'solitude', weight: 2},
    {word: 'alone', weight: 1},
    {word: 'isolation', weight: 2},
    {word: 'apart', weight: 2},
    {word: 'desolate', weight: 3},
    {word: 'empty', weight: 2},
    {word: 'friendless', weight: 3},
    {word: 'separate', weight: 2},
    {word: 'lost', weight: 2},
    {word: 'remoteness', weight: 3},
    {word: 'abandoned', weight: 2},
    {word: 'alienation', weight: 3},
    {word: 'quiet', weight: 2},
    {word: 'withdrawn', weight: 3},
    
    // More specific (4-7)
    {word: 'social-isolation', weight: 4},
    {word: 'emotional-loneliness', weight: 5},
    {word: 'existential-loneliness', weight: 6},
    {word: 'chronic-loneliness', weight: 5},
    {word: 'loneliness-epidemic', weight: 6},
    {word: 'social-anxiety', weight: 4},
    {word: 'introversion', weight: 4},
    {word: 'hermit-mode', weight: 5},
    {word: 'ghosting-friends', weight: 6},
    {word: 'social-battery-drained', weight: 6},
    {word: 'lonely-in-crowd', weight: 5},
    {word: 'pandemic-loneliness', weight: 6},
    {word: 'digital-loneliness', weight: 6},
    {word: 'bedroom-pop-vibes', weight: 7},
    
    // Niche/specific (7-10)
    {word: 'hikikomori', weight: 8},
    {word: 'solipsism', weight: 8},
    {word: 'anomie', weight: 8},
    {word: 'fernweh', weight: 9},
    {word: 'hiraeth', weight: 9},
    {word: 'saudade', weight: 8},
    {word: 'sehnsucht', weight: 9},
    {word: 'mono-no-aware', weight: 9},
    {word: 'ubuntu-absence', weight: 9},
    {word: 'social-anhedonia', weight: 7},
    {word: 'avoidant-attachment', weight: 7},
    {word: 'misanthropy', weight: 6},
    {word: 'hermitage', weight: 7},
    {word: 'anchorite', weight: 9}
  ],

  'Anger': [
    // Generic (1-3)
    {word: 'anger', weight: 1},
    {word: 'rage', weight: 2},
    {word: 'fury', weight: 2},
    {word: 'wrath', weight: 3},
    {word: 'resentment', weight: 3},
    {word: 'annoyance', weight: 2},
    {word: 'hate', weight: 2},
    {word: 'fierce', weight: 2},
    {word: 'resent', weight: 2},
    {word: 'frustration', weight: 2},
    {word: 'vengeance', weight: 3},
    {word: 'mad', weight: 1},
    {word: 'furious', weight: 2},
    {word: 'irritation', weight: 2},
    {word: 'aggression', weight: 3},
    {word: 'hostility', weight: 3},
    {word: 'grudge', weight: 3},
    
    // More specific (4-7)
    {word: 'righteous-anger', weight: 4},
    {word: 'road-rage', weight: 4},
    {word: 'passive-aggressive', weight: 4},
    {word: 'anger-management', weight: 5},
    {word: 'hot-headed', weight: 4},
    {word: 'short-fuse', weight: 4},
    {word: 'seeing-red', weight: 4},
    {word: 'triggered', weight: 4},
    {word: 'livid', weight: 4},
    {word: 'seething', weight: 4},
    {word: 'boiling-point', weight: 4},
    {word: 'explosive-temper', weight: 5},
    {word: 'cold-fury', weight: 5},
    {word: 'bitter-resentment', weight: 5},
    {word: 'vindictive', weight: 5},
    
    // Niche/specific (7-10)
    {word: 'intermittent-explosive-disorder', weight: 8},
    {word: 'displaced-anger', weight: 6},
    {word: 'suppressed-rage', weight: 6},
    {word: 'misplaced-anger', weight: 6},
    {word: 'berserker-rage', weight: 7},
    {word: 'apoplectic', weight: 8},
    {word: 'incandescent', weight: 7},
    {word: 'choleric', weight: 8},
    {word: 'irascible', weight: 8},
    {word: 'truculent', weight: 8},
    {word: 'bellicose', weight: 7},
    {word: 'pugnacious', weight: 8},
    {word: 'wrathful', weight: 6},
    {word: 'splenetic', weight: 9}
  ],

  'Compassion': [
    // Generic (1-3)
    {word: 'compassion', weight: 1},
    {word: 'empathy', weight: 2},
    {word: 'kindness', weight: 1},
    {word: 'sympathy', weight: 2},
    {word: 'care', weight: 1},
    {word: 'help', weight: 1},
    {word: 'mercy', weight: 2},
    {word: 'forgiveness', weight: 2},
    {word: 'tenderness', weight: 2},
    {word: 'charity', weight: 2},
    {word: 'altruism', weight: 3},
    {word: 'support', weight: 2},
    {word: 'love', weight: 1},
    {word: 'gentle', weight: 2},
    {word: 'softness', weight: 2},
    
    // More specific (4-7)
    {word: 'self-compassion', weight: 4},
    {word: 'emotional-support', weight: 4},
    {word: 'active-listening', weight: 4},
    {word: 'unconditional-love', weight: 4},
    {word: 'holding-space', weight: 5},
    {word: 'trauma-informed', weight: 6},
    {word: 'restorative-justice', weight: 6},
    {word: 'loving-kindness', weight: 5},
    {word: 'mindful-compassion', weight: 5},
    {word: 'compassion-fatigue', weight: 6},
    {word: 'radical-acceptance', weight: 5},
    {word: 'wounded-healer', weight: 6},
    {word: 'caregiver-burnout', weight: 6},
    {word: 'secondary-trauma', weight: 6},
    
    // Niche/specific (7-10)
    {word: 'metta', weight: 8},
    {word: 'karuna', weight: 8},
    {word: 'mudita', weight: 9},
    {word: 'upekkha', weight: 9},
    {word: 'bodhisattva', weight: 8},
    {word: 'agape', weight: 7},
    {word: 'ubuntu', weight: 8},
    {word: 'ahimsa', weight: 8},
    {word: 'tonglen', weight: 9},
    {word: 'compassion-focused-therapy', weight: 7},
    {word: 'self-compassion-break', weight: 7},
    {word: 'fierce-compassion', weight: 7},
    {word: 'idiot-compassion', weight: 8},
    {word: 'philantropy', weight: 4}
  ],

  'Fear': [
    // Generic (1-3)
    {word: 'fear', weight: 1},
    {word: 'terror', weight: 2},
    {word: 'panic', weight: 2},
    {word: 'fright', weight: 2},
    {word: 'dread', weight: 2},
    {word: 'scared', weight: 1},
    {word: 'anxiety', weight: 2},
    {word: 'worry', weight: 2},
    {word: 'nervous', weight: 2},
    {word: 'threat', weight: 2},
    {word: 'danger', weight: 2},
    {word: 'apprehension', weight: 3},
    {word: 'phobia', weight: 3},
    {word: 'alarm', weight: 2},
    {word: 'shock', weight: 2},
    
    // More specific (4-7)
    {word: 'anxiety-disorder', weight: 4},
    {word: 'panic-attack', weight: 4},
    {word: 'social-anxiety', weight: 4},
    {word: 'flight-or-fight', weight: 4},
    {word: 'adrenaline-rush', weight: 4},
    {word: 'phobic-response', weight: 5},
    {word: 'catastrophic-thinking', weight: 5},
    {word: 'anticipatory-anxiety', weight: 5},
    {word: 'existential-dread', weight: 5},
    {word: 'impostor-syndrome', weight: 5},
    {word: 'fear-of-missing-out', weight: 5},
    {word: 'analysis-paralysis', weight: 5},
    {word: 'decision-fatigue', weight: 5},
    {word: 'performance-anxiety', weight: 4},
    
    // Niche/specific (7-10)
    {word: 'agoraphobia', weight: 6},
    {word: 'claustrophobia', weight: 6},
    {word: 'thanatophobia', weight: 7},
    {word: 'trypophobia', weight: 7},
    {word: 'nomophobia', weight: 7},
    {word: 'fomo', weight: 6},
    {word: 'jomo', weight: 7},
    {word: 'eco-anxiety', weight: 6},
    {word: 'climate-grief', weight: 6},
    {word: 'scopophobia', weight: 8},
    {word: 'phonophobia', weight: 8},
    {word: 'anthropophobia', weight: 8},
    {word: 'nyctophobia', weight: 7},
    {word: 'technophobia', weight: 6}
  ],

  'Family': [
    // Generic (1-3)
    {word: 'father', weight: 1},
    {word: 'mother', weight: 1},
    {word: 'parent', weight: 1},
    {word: 'child', weight: 1},
    {word: 'family', weight: 1},
    {word: 'son', weight: 1},
    {word: 'daughter', weight: 1},
    {word: 'husband', weight: 1},
    {word: 'wife', weight: 1},
    {word: 'sibling', weight: 2},
    {word: 'brother', weight: 1},
    {word: 'sister', weight: 1},
    {word: 'relative', weight: 2},
    {word: 'grandparent', weight: 2},
    {word: 'kin', weight: 2},
    {word: 'home', weight: 1},
    {word: 'household', weight: 2},
    {word: 'birth', weight: 2},
    {word: 'marriage', weight: 2},
    {word: 'bond', weight: 2},
    {word: 'support', weight: 2},
    {word: 'love', weight: 1},
    
    // More specific (4-7)
    {word: 'nuclear-family', weight: 4},
    {word: 'extended-family', weight: 4},
    {word: 'blended-family', weight: 5},
    {word: 'chosen-family', weight: 5},
    {word: 'single-parent', weight: 4},
    {word: 'helicopter-parent', weight: 5},
    {word: 'tiger-parent', weight: 6},
    {word: 'empty-nest', weight: 5},
    {word: 'sandwich-generation', weight: 6},
    {word: 'family-dynamics', weight: 4},
    {word: 'dysfunctional-family', weight: 5},
    {word: 'toxic-family', weight: 5},
    {word: 'estranged', weight: 5},
    {word: 'family-therapy', weight: 5},
    {word: 'generational-trauma', weight: 6},
    {word: 'family-of-origin', weight: 5},
    {word: 'co-parenting', weight: 5},
    {word: 'step-family', weight: 4},
    {word: 'foster-family', weight: 5},
    {word: 'adoptive-family', weight: 5},
    
    // Niche/specific (7-10)
    {word: 'enmeshment', weight: 7},
    {word: 'parentification', weight: 7},
    {word: 'golden-child', weight: 6},
    {word: 'scapegoat', weight: 6},
    {word: 'no-contact', weight: 6},
    {word: 'low-contact', weight: 6},
    {word: 'narcissistic-parent', weight: 6},
    {word: 'attachment-styles', weight: 6},
    {word: 'intergenerational-patterns', weight: 7},
    {word: 'family-constellation', weight: 7},
    {word: 'genogram', weight: 8},
    {word: 'bowen-theory', weight: 8},
    {word: 'differentiation', weight: 7},
    {word: 'triangulation', weight: 7},
    {word: 'cutoff', weight: 6},
    {word: 'multigenerational-transmission', weight: 8},
    {word: 'emotional-fusion', weight: 7},
    {word: 'family-projection-process', weight: 8},
    {word: 'sibling-position', weight: 6},
    {word: 'societal-regression', weight: 8}
  ],

  'Friendship': [
    // Generic (1-3)
    {word: 'friend', weight: 1},
    {word: 'companionship', weight: 2},
    {word: 'ally', weight: 2},
    {word: 'trust', weight: 2},
    {word: 'bond', weight: 2},
    {word: 'support', weight: 2},
    {word: 'partner', weight: 2},
    {word: 'comrade', weight: 3},
    {word: 'pal', weight: 2},
    {word: 'buddy', weight: 2},
    {word: 'confidant', weight: 3},
    {word: 'team', weight: 2},
    {word: 'agreement', weight: 2},
    {word: 'relationship', weight: 2},
    
    // More specific (4-7)
    {word: 'best-friend', weight: 3},
    {word: 'bff', weight: 4},
    {word: 'ride-or-die', weight: 5},
    {word: 'bestie', weight: 4},
    {word: 'squad', weight: 4},
    {word: 'crew', weight: 4},
    {word: 'inner-circle', weight: 4},
    {word: 'platonic-soulmate', weight: 5},
    {word: 'friendship-breakup', weight: 5},
    {word: 'fair-weather-friend', weight: 5},
    {word: 'toxic-friend', weight: 5},
    {word: 'friend-zone', weight: 4},
    {word: 'social-circle', weight: 4},
    {word: 'acquaintance', weight: 3},
    {word: 'mutual-friend', weight: 4},
    {word: 'childhood-friend', weight: 4},
    {word: 'work-friend', weight: 4},
    {word: 'internet-friend', weight: 5},
    {word: 'long-distance-friendship', weight: 5},
    
    // Niche/specific (7-10)
    {word: 'parasocial-relationship', weight: 7},
    {word: 'friendship-recession', weight: 7},
    {word: 'social-battery', weight: 6},
    {word: 'friend-ghosting', weight: 6},
    {word: 'friendship-audit', weight: 7},
    {word: 'bromance', weight: 6},
    {word: 'womance', weight: 6},
    {word: 'framily', weight: 7},
    {word: 'emotional-labor', weight: 6},
    {word: 'codependent-friendship', weight: 6},
    {word: 'one-sided-friendship', weight: 5},
    {word: 'friendship-maintenance', weight: 6},
    {word: 'dunbar-number', weight: 8},
    {word: 'philophilia', weight: 9},
    {word: 'amicitia', weight: 8},
    {word: 'ubuntu-friendship', weight: 8}
  ],

  'Parenthood': [
    // Generic (1-3)
    {word: 'parent', weight: 1},
    {word: 'child', weight: 1},
    {word: 'father', weight: 1},
    {word: 'mother', weight: 1},
    {word: 'babies', weight: 2},
    {word: 'offspring', weight: 3},
    {word: 'nurture', weight: 2},
    {word: 'care', weight: 1},
    {word: 'teach', weight: 2},
    {word: 'guide', weight: 2},
    {word: 'love', weight: 1},
    {word: 'protection', weight: 2},
    {word: 'baby', weight: 1},
    {word: 'family', weight: 1},
    
    // More specific (4-7)
    {word: 'new-parent', weight: 4},
    {word: 'sleep-deprivation', weight: 4},
    {word: 'baby-blues', weight: 5},
    {word: 'postpartum-depression', weight: 5},
    {word: 'breastfeeding', weight: 4},
    {word: 'formula-feeding', weight: 4},
    {word: 'sleep-training', weight: 5},
    {word: 'terrible-twos', weight: 4},
    {word: 'potty-training', weight: 4},
    {word: 'helicopter-parenting', weight: 5},
    {word: 'free-range-parenting', weight: 6},
    {word: 'attachment-parenting', weight: 5},
    {word: 'gentle-parenting', weight: 5},
    {word: 'authoritative-parenting', weight: 5},
    {word: 'permissive-parenting', weight: 5},
    {word: 'tiger-parenting', weight: 6},
    {word: 'single-parenting', weight: 4},
    {word: 'co-parenting', weight: 5},
    {word: 'stay-at-home-parent', weight: 4},
    {word: 'working-parent', weight: 4},
    
    // Niche/specific (7-10)
    {word: 'matrescence', weight: 8},
    {word: 'patrescence', weight: 9},
    {word: 'fourth-trimester', weight: 6},
    {word: 'mom-guilt', weight: 5},
    {word: 'dad-guilt', weight: 6},
    {word: 'parental-burnout', weight: 6},
    {word: 'intensive-parenting', weight: 6},
    {word: 'concerted-cultivation', weight: 7},
    {word: 'natural-growth', weight: 7},
    {word: 'snowplow-parenting', weight: 7},
    {word: 'lawnmower-parenting', weight: 7},
    {word: 'curling-parenting', weight: 8},
    {word: 'dolphin-parenting', weight: 7},
    {word: 'elephant-parenting', weight: 7},
    {word: 'lighthouse-parenting', weight: 7},
    {word: 'reparenting', weight: 6},
    {word: 'inner-child-work', weight: 6},
    {word: 'generational-cycles', weight: 6}
  ],

  'Marriage': [
    // Generic (1-3)
    {word: 'marriage', weight: 1},
    {word: 'wedding', weight: 1},
    {word: 'spouse', weight: 2},
    {word: 'partner', weight: 2},
    {word: 'bride', weight: 2},
    {word: 'groom', weight: 2},
    {word: 'union', weight: 2},
    {word: 'love', weight: 1},
    {word: 'commitment', weight: 2},
    {word: 'vows', weight: 2},
    {word: 'rings', weight: 2},
    {word: 'ceremony', weight: 2},
    {word: 'celebration', weight: 2},
    
    // More specific (4-7)
    {word: 'newlywed', weight: 3},
    {word: 'honeymoon-phase', weight: 4},
    {word: 'marital-bliss', weight: 4},
    {word: 'couples-therapy', weight: 5},
    {word: 'marriage-counseling', weight: 5},
    {word: 'prenup', weight: 4},
    {word: 'common-law', weight: 4},
    {word: 'civil-union', weight: 4},
    {word: 'domestic-partnership', weight: 5},
    {word: 'same-sex-marriage', weight: 4},
    {word: 'interfaith-marriage', weight: 5},
    {word: 'interracial-marriage', weight: 5},
    {word: 'arranged-marriage', weight: 5},
    {word: 'love-marriage', weight: 4},
    {word: 'trial-separation', weight: 5},
    {word: 'legal-separation', weight: 5},
    {word: 'divorce', weight: 3},
    {word: 'annulment', weight: 4},
    {word: 'remarriage', weight: 4},
    {word: 'blended-family', weight: 4},
    
    // Niche/specific (7-10)
    {word: 'gottman-method', weight: 8},
    {word: 'four-horsemen', weight: 7},
    {word: 'stonewalling', weight: 6},
    {word: 'contempt', weight: 5},
    {word: 'criticism', weight: 4},
    {word: 'defensiveness', weight: 5},
    {word: 'emotional-flooding', weight: 6},
    {word: 'repair-attempts', weight: 6},
    {word: 'love-languages', weight: 5},
    {word: 'attachment-styles', weight: 6},
    {word: 'secure-attachment', weight: 6},
    {word: 'anxious-attachment', weight: 6},
    {word: 'avoidant-attachment', weight: 6},
    {word: 'disorganized-attachment', weight: 7},
    {word: 'enmeshment', weight: 6},
    {word: 'differentiation', weight: 7},
    {word: 'triangulation', weight: 7},
    {word: 'codependency', weight: 5},
    {word: 'conscious-uncoupling', weight: 7},
    {word: 'gray-divorce', weight: 7}
  ],

  'Womanhood': [
    // Generic (1-3)
    {word: 'woman', weight: 1},
    {word: 'female', weight: 1},
    {word: 'feminine', weight: 2},
    {word: 'mother', weight: 1},
    {word: 'daughter', weight: 1},
    {word: 'girl', weight: 1},
    {word: 'sister', weight: 1},
    {word: 'motherhood', weight: 2},
    {word: 'strength', weight: 2},
    {word: 'gender', weight: 2},
    {word: 'empowerment', weight: 3},
    {word: 'identity', weight: 2},
    {word: 'rights', weight: 2},
    {word: 'freedom', weight: 2},
    {word: 'voice', weight: 2},
    {word: 'beauty', weight: 2},
    
    // More specific (4-7)
    {word: 'feminist', weight: 4},
    {word: 'feminism', weight: 4},
    {word: 'sisterhood', weight: 4},
    {word: 'girl-power', weight: 4},
    {word: 'women-supporting-women', weight: 5},
    {word: 'glass-ceiling', weight: 5},
    {word: 'wage-gap', weight: 5},
    {word: 'reproductive-rights', weight: 5},
    {word: 'body-autonomy', weight: 5},
    {word: 'menstruation', weight: 4},
    {word: 'menopause', weight: 4},
    {word: 'pregnancy', weight: 3},
    {word: 'childbirth', weight: 3},
    {word: 'working-mom', weight: 4},
    {word: 'stay-at-home-mom', weight: 4},
    {word: 'career-woman', weight: 4},
    {word: 'single-woman', weight: 4},
    {word: 'independent-woman', weight: 4},
    
    // Niche/specific (7-10)
    {word: 'divine-feminine', weight: 6},
    {word: 'sacred-feminine', weight: 6},
    {word: 'goddess-energy', weight: 6},
    {word: 'maiden-mother-crone', weight: 7},
    {word: 'menstrual-cycle-awareness', weight: 7},
    {word: 'moon-cycle', weight: 6},
    {word: 'red-tent', weight: 7},
    {word: 'women-circles', weight: 6},
    {word: 'maternal-feminism', weight: 7},
    {word: 'intersectional-feminism', weight: 6},
    {word: 'womxn', weight: 7},
    {word: 'herstory', weight: 6},
    {word: 'matriarchy', weight: 6},
    {word: 'patriarchal-conditioning', weight: 6},
    {word: 'internalized-misogyny', weight: 6},
    {word: 'male-gaze', weight: 6},
    {word: 'female-gaze', weight: 6},
    {word: 'pick-me-girl', weight: 6},
    {word: 'girls-girl', weight: 6},
    {word: 'hot-girl-summer', weight: 6},
    {word: 'soft-life', weight: 6},
    {word: 'feminine-rage', weight: 6},
    {word: 'wild-woman', weight: 6}
  ],

  'Masculinity': [
    // Generic (1-3)
    {word: 'man', weight: 1},
    {word: 'male', weight: 1},
    {word: 'father', weight: 1},
    {word: 'son', weight: 1},
    {word: 'brother', weight: 1},
    {word: 'strength', weight: 2},
    {word: 'power', weight: 2},
    {word: 'identity', weight: 2},
    {word: 'masculine', weight: 2},
    {word: 'responsibility', weight: 2},
    {word: 'tradition', weight: 2},
    {word: 'bravery', weight: 2},
    {word: 'emotion', weight: 2},
    {word: 'silence', weight: 2},
    {word: 'honor', weight: 3},
    
    // More specific (4-7)
    {word: 'toxic-masculinity', weight: 5},
    {word: 'healthy-masculinity', weight: 5},
    {word: 'traditional-masculinity', weight: 4},
    {word: 'emotional-suppression', weight: 5},
    {word: 'boys-dont-cry', weight: 5},
    {word: 'man-up', weight: 4},
    {word: 'breadwinner', weight: 4},
    {word: 'provider', weight: 4},
    {word: 'protector', weight: 4},
    {word: 'alpha-male', weight: 5},
    {word: 'beta-male', weight: 5},
    {word: 'sigma-male', weight: 6},
    {word: 'mens-rights', weight: 5},
    {word: 'father-figure', weight: 4},
    {word: 'absent-father', weight: 4},
    {word: 'emotionally-unavailable', weight: 5},
    {word: 'stoicism', weight: 4},
    {word: 'machismo', weight: 5},
    
    // Niche/specific (7-10)
    {word: 'hegemonic-masculinity', weight: 7},
    {word: 'fragile-masculinity', weight: 6},
    {word: 'performative-masculinity', weight: 6},
    {word: 'masculine-norms', weight: 6},
    {word: 'man-box', weight: 7},
    {word: 'emotional-labor-avoidance', weight: 7},
    {word: 'male-privilege', weight: 5},
    {word: 'mansplaining', weight: 6},
    {word: 'manspreading', weight: 6},
    {word: 'manosphere', weight: 7},
    {word: 'incel', weight: 6},
    {word: 'mgtow', weight: 7},
    {word: 'redpill', weight: 6},
    {word: 'pickup-artist', weight: 6},
    {word: 'mens-liberation', weight: 7},
    {word: 'new-man', weight: 6},
    {word: 'sensitive-new-age-guy', weight: 7},
    {word: 'metrosexual', weight: 6},
    {word: 'lumbersexual', weight: 7},
    {word: 'dadcore', weight: 7},
    {word: 'soft-masculinity', weight: 6},
    {word: 'divine-masculine', weight: 6}
  ],

  'Social Stigma': [
    // Generic (1-3)
    {word: 'stigma', weight: 1},
    {word: 'shame', weight: 2},
    {word: 'outsider', weight: 2},
    {word: 'discrimination', weight: 2},
    {word: 'prejudice', weight: 2},
    {word: 'label', weight: 2},
    {word: 'taboo', weight: 3},
    {word: 'gossip', weight: 2},
    {word: 'oppression', weight: 3},
    {word: 'isolated', weight: 2},
    {word: 'mockery', weight: 3},
    {word: 'rejection', weight: 2},
    {word: 'bias', weight: 2},
    {word: 'culture', weight: 2},
    
    // More specific (4-7)
    {word: 'mental-health-stigma', weight: 5},
    {word: 'social-outcast', weight: 4},
    {word: 'pariah', weight: 4},
    {word: 'blacklisted', weight: 4},
    {word: 'cancel-culture', weight: 5},
    {word: 'public-shaming', weight: 5},
    {word: 'victim-blaming', weight: 5},
    {word: 'slut-shaming', weight: 5},
    {word: 'body-shaming', weight: 5},
    {word: 'fat-shaming', weight: 5},
    {word: 'ageism', weight: 4},
    {word: 'racism', weight: 4},
    {word: 'sexism', weight: 4},
    {word: 'homophobia', weight: 4},
    {word: 'transphobia', weight: 5},
    {word: 'ableism', weight: 5},
    {word: 'classism', weight: 5},
    {word: 'colorism', weight: 5},
    
    // Niche/specific (7-10)
    {word: 'intersectional-stigma', weight: 7},
    {word: 'courtesy-stigma', weight: 8},
    {word: 'felt-stigma', weight: 7},
    {word: 'enacted-stigma', weight: 8},
    {word: 'self-stigma', weight: 6},
    {word: 'structural-stigma', weight: 7},
    {word: 'stigma-by-association', weight: 7},
    {word: 'moral-panic', weight: 6},
    {word: 'scapegoating', weight: 6},
    {word: 'othering', weight: 6},
    {word: 'dehumanization', weight: 6},
    {word: 'social-death', weight: 7},
    {word: 'symbolic-violence', weight: 8},
    {word: 'microaggressions', weight: 6},
    {word: 'gaslighting', weight: 5},
    {word: 'tone-policing', weight: 6},
    {word: 'respectability-politics', weight: 7},
    {word: 'purity-culture', weight: 6},
    {word: 'virtue-signaling', weight: 6}
  ],

  'Mental Health': [
    // Generic (weight 1-3)
    {word: 'mental-health', weight: 1},
    {word: 'wellness', weight: 1},
    {word: 'stress', weight: 1},
    {word: 'anxiety', weight: 1},
    {word: 'depression', weight: 1},
    {word: 'therapy', weight: 1},
    {word: 'counseling', weight: 2},
    {word: 'support', weight: 1},
    {word: 'healing', weight: 2},
    {word: 'recovery', weight: 2},
    {word: 'coping', weight: 2},
    {word: 'mindfulness', weight: 2},
    {word: 'self-care', weight: 2},
    {word: 'wellbeing', weight: 2},
    {word: 'emotions', weight: 1},
    {word: 'feelings', weight: 1},
    {word: 'mood', weight: 1},
    {word: 'resilience', weight: 2},
    {word: 'balance', weight: 2},
    {word: 'burnout', weight: 2},
    {word: 'overwhelmed', weight: 2},
    {word: 'exhausted', weight: 2},
    {word: 'psychiatrist', weight: 3},
    {word: 'psychologist', weight: 3},
    {word: 'medication', weight: 3},
    {word: 'treatment', weight: 2},

    // More specific contemporary (weight 4-7)
    {word: 'trauma-informed', weight: 4},
    {word: 'mindful-breathing', weight: 4},
    {word: 'grounding-techniques', weight: 5},
    {word: 'emotional-regulation', weight: 4},
    {word: 'trigger-warning', weight: 4},
    {word: 'safe-space', weight: 4},
    {word: 'boundaries', weight: 3},
    {word: 'toxic-positivity', weight: 5},
    {word: 'mental-load', weight: 5},
    {word: 'people-pleasing', weight: 4},
    {word: 'imposter-syndrome', weight: 5},
    {word: 'doom-scrolling', weight: 6},
    {word: 'digital-detox', weight: 5},
    {word: 'social-battery', weight: 6},
    {word: 'overstimulation', weight: 5},
    {word: 'sensory-overload', weight: 5},
    {word: 'emotional-burnout', weight: 4},
    {word: 'compassion-fatigue', weight: 5},
    {word: 'decision-fatigue', weight: 5},
    {word: 'analysis-paralysis', weight: 5},
    {word: 'catastrophizing', weight: 4},
    {word: 'overthinking', weight: 3},
    {word: 'rumination', weight: 4},
    {word: 'self-sabotage', weight: 4},
    {word: 'perfectionism', weight: 3},
    {word: 'procrastination', weight: 3},
    {word: 'avoidance', weight: 4},
    {word: 'hypervigilance', weight: 5},
    {word: 'fight-or-flight', weight: 4},
    {word: 'freeze-response', weight: 5},
    {word: 'dissociation', weight: 5},

    // Very specific/niche contemporary (weight 7-10)
    {word: 'spoon-theory', weight: 8},
    {word: 'masking', weight: 7},
    {word: 'unmasking', weight: 8},
    {word: 'neurodivergent', weight: 7},
    {word: 'neurotypical', weight: 7},
    {word: 'stimming', weight: 8},
    {word: 'sensory-seeking', weight: 8},
    {word: 'rejection-sensitive-dysphoria', weight: 9},
    {word: 'executive-dysfunction', weight: 8},
    {word: 'time-blindness', weight: 8},
    {word: 'hyperfocus', weight: 7},
    {word: 'dopamine-seeking', weight: 8},
    {word: 'dopamine-detox', weight: 8},
    {word: 'micro-dosing', weight: 8},
    {word: 'somatic-therapy', weight: 7},
    {word: 'emdr', weight: 8},
    {word: 'dbt', weight: 8},
    {word: 'cbt', weight: 7},
    {word: 'act-therapy', weight: 9},
    {word: 'polyvagal-theory', weight: 9},
    {word: 'vagal-tone', weight: 9},
    {word: 'co-regulation', weight: 8},
    {word: 'window-of-tolerance', weight: 9},
    {word: 'nervous-system-regulation', weight: 8},
    {word: 'attachment-styles', weight: 7},
    {word: 'secure-attachment', weight: 8},
    {word: 'anxious-attachment', weight: 8},
    {word: 'avoidant-attachment', weight: 8},
    {word: 'disorganized-attachment', weight: 9},
    {word: 'trauma-bonding', weight: 7},
    {word: 'fawn-response', weight: 8},
    {word: 'parentification', weight: 8},
    {word: 'enmeshment', weight: 8},
    {word: 'emotional-dysregulation', weight: 7},
    {word: 'alexithymia', weight: 9},
    {word: 'anhedonia', weight: 8},

    // Clinical/diagnostic terms (weight 6-10)
    {word: 'ptsd', weight: 6},
    {word: 'c-ptsd', weight: 7},
    {word: 'adhd', weight: 6},
    {word: 'autism', weight: 6},
    {word: 'asd', weight: 7},
    {word: 'bipolar', weight: 6},
    {word: 'bpd', weight: 7},
    {word: 'ocd', weight: 6},
    {word: 'gad', weight: 7},
    {word: 'panic-disorder', weight: 6},
    {word: 'social-anxiety', weight: 5},
    {word: 'agoraphobia', weight: 7},
    {word: 'specific-phobia', weight: 7},
    {word: 'eating-disorder', weight: 5},
    {word: 'anorexia', weight: 6},
    {word: 'bulimia', weight: 6},
    {word: 'binge-eating', weight: 6},
    {word: 'body-dysmorphia', weight: 6},
    {word: 'seasonal-affective-disorder', weight: 7},
    {word: 'major-depressive-disorder', weight: 7},
    {word: 'persistent-depressive-disorder', weight: 8},
    {word: 'cyclothymia', weight: 9},
    {word: 'hypomania', weight: 8},
    {word: 'mania', weight: 7},
    {word: 'mixed-episode', weight: 8},
    {word: 'rapid-cycling', weight: 8},
    {word: 'psychosis', weight: 7},
    {word: 'hallucinations', weight: 7},
    {word: 'delusions', weight: 7},
    {word: 'paranoia', weight: 6},
    {word: 'schizophrenia', weight: 7},
    {word: 'schizoaffective', weight: 9},

    // Treatment and medication terms (weight 6-9)
    {word: 'antidepressant', weight: 6},
    {word: 'ssri', weight: 7},
    {word: 'snri', weight: 8},
    {word: 'anxiolytic', weight: 8},
    {word: 'mood-stabilizer', weight: 7},
    {word: 'antipsychotic', weight: 7},
    {word: 'stimulant', weight: 6},
    {word: 'non-stimulant', weight: 7},
    {word: 'benzodiazepine', weight: 8},
    {word: 'therapeutic-alliance', weight: 7},
    {word: 'transference', weight: 8},
    {word: 'countertransference', weight: 9},
    {word: 'psychodynamic', weight: 7},
    {word: 'humanistic-therapy', weight: 8},
    {word: 'gestalt-therapy', weight: 9},
    {word: 'narrative-therapy', weight: 8},
    {word: 'family-systems', weight: 7},
    {word: 'group-therapy', weight: 6},
    {word: 'intensive-outpatient', weight: 7},
    {word: 'partial-hospitalization', weight: 8},
    {word: 'inpatient', weight: 6},
    {word: 'crisis-intervention', weight: 7},
    {word: 'suicide-ideation', weight: 6},
    {word: 'self-harm', weight: 5},
    {word: 'safety-plan', weight: 6},

    // Cultural and social terms (weight 5-8)
    {word: 'mental-health-stigma', weight: 5},
    {word: 'cultural-competency', weight: 7},
    {word: 'microaggressions', weight: 6},
    {word: 'minority-stress', weight: 7},
    {word: 'intersectionality', weight: 6},
    {word: 'social-determinants', weight: 7},
    {word: 'health-equity', weight: 6},
    {word: 'peer-support', weight: 5},
    {word: 'lived-experience', weight: 6},
    {word: 'mental-health-advocate', weight: 6},
    {word: 'community-mental-health', weight: 7},
    {word: 'teletherapy', weight: 6},
    {word: 'telehealth', weight: 5},
    {word: 'crisis-hotline', weight: 6},
    {word: 'employee-assistance', weight: 7},
    {word: 'workplace-wellness', weight: 6}
],

  'Political Rebellion': [
    // Generic (1-3)
    {word: 'revolt', weight: 2},
    {word: 'rebel', weight: 2},
    {word: 'protest', weight: 2},
    {word: 'revolution', weight: 2},
    {word: 'uprising', weight: 3},
    {word: 'resistance', weight: 2},
    {word: 'fight', weight: 1},
    {word: 'freedom', weight: 2},
    {word: 'tyranny', weight: 3},
    {word: 'oppression', weight: 2},
    {word: 'liberation', weight: 3},
    {word: 'democracy', weight: 2},
    {word: 'insurrection', weight: 3},
    {word: 'power', weight: 1},
    {word: 'battle', weight: 2},
    {word: 'struggle', weight: 2},
    {word: 'justice', weight: 2},
    
    // More specific (4-7)
    {word: 'civil-disobedience', weight: 4},
    {word: 'civil-rights', weight: 4},
    {word: 'activism', weight: 4},
    {word: 'social-movement', weight: 4},
    {word: 'grassroots', weight: 4},
    {word: 'underground', weight: 4},
    {word: 'guerrilla-warfare', weight: 5},
    {word: 'partisan', weight: 5},
    {word: 'insurgency', weight: 5},
    {word: 'coup', weight: 5},
    {word: 'regime-change', weight: 5},
    {word: 'dissent', weight: 4},
    {word: 'counter-culture', weight: 5},
    {word: 'anti-establishment', weight: 5},
    {word: 'radical', weight: 4},
    {word: 'revolutionary', weight: 4},
    {word: 'anarchist', weight: 5},
    {word: 'socialist', weight: 4},
    {word: 'communist', weight: 4},
    
    // Niche/specific (7-10)
    {word: 'praxis', weight: 7},
    {word: 'consciousness-raising', weight: 6},
    {word: 'direct-action', weight: 6},
    {word: 'militant', weight: 5},
    {word: 'subversive', weight: 6},
    {word: 'sedition', weight: 7},
    {word: 'sabotage', weight: 6},
    {word: 'agitprop', weight: 8},
    {word: 'false-consciousness', weight: 7},
    {word: 'hegemony', weight: 7},
    {word: 'counter-hegemonic', weight: 8},
    {word: 'intersectionality', weight: 6},
    {word: 'solidarity', weight: 5},
    {word: 'prefigurative-politics', weight: 8},
    {word: 'dual-power', weight: 8},
    {word: 'mutual-aid', weight: 6},
    {word: 'black-bloc', weight: 7},
    {word: 'culture-jamming', weight: 7},
    {word: 'hacktivism', weight: 7},
    {word: 'slacktivism', weight: 6},
    {word: 'clicktivism', weight: 6}
  ],

  'Identity': [
    // Generic (1-3)
    {word: 'identity', weight: 1},
    {word: 'self', weight: 1},
    {word: 'ego', weight: 2},
    {word: 'myself', weight: 1},
    {word: 'being', weight: 2},
    {word: 'who am i', weight: 2},
    {word: 'personality', weight: 2},
    {word: 'think', weight: 1},
    {word: 'reflect', weight: 2},
    {word: 'soul', weight: 2},
    {word: 'nature', weight: 2},
    {word: 'individual', weight: 2},
    {word: 'character', weight: 2},
    {word: 'mask', weight: 3},
    {word: 'role', weight: 2},
    
    // More specific (4-7)
    {word: 'self-discovery', weight: 4},
    {word: 'self-awareness', weight: 4},
    {word: 'authenticity', weight: 4},
    {word: 'inner-self', weight: 4},
    {word: 'true-self', weight: 4},
    {word: 'false-self', weight: 5},
    {word: 'identity-crisis', weight: 5},
    {word: 'coming-of-age', weight: 4},
    {word: 'personal-growth', weight: 4},
    {word: 'self-actualization', weight: 5},
    {word: 'individuation', weight: 5},
    {word: 'persona', weight: 5},
    {word: 'shadow-self', weight: 6},
    {word: 'collective-identity', weight: 5},
    {word: 'cultural-identity', weight: 5},
    {word: 'gender-identity', weight: 5},
    {word: 'sexual-identity', weight: 5},
    {word: 'racial-identity', weight: 5},
    {word: 'ethnic-identity', weight: 5},
    
    // Niche/specific (7-10)
    {word: 'intersectional-identity', weight: 6},
    {word: 'multiple-identities', weight: 6},
    {word: 'code-switching', weight: 6},
    {word: 'double-consciousness', weight: 7},
    {word: 'third-culture-kid', weight: 7},
    {word: 'diaspora-identity', weight: 7},
    {word: 'liminal-identity', weight: 8},
    {word: 'fluid-identity', weight: 6},
    {word: 'performative-identity', weight: 7},
    {word: 'constructed-identity', weight: 7},
    {word: 'essential-identity', weight: 7},
    {word: 'narrative-identity', weight: 7},
    {word: 'digital-identity', weight: 6},
    {word: 'online-persona', weight: 6},
    {word: 'identity-politics', weight: 6},
    {word: 'identity-formation', weight: 6},
    {word: 'eriksonian-stages', weight: 8},
    {word: 'moratorium', weight: 7},
    {word: 'foreclosure', weight: 7},
    {word: 'diffusion', weight: 6},
    {word: 'achievement', weight: 5}
  ],
  'Memory': [
    // Generic (1-3)
    {word: 'memory', weight: 1},
    {word: 'remember', weight: 1},
    {word: 'past', weight: 1},
    {word: 'childhood', weight: 2},
    {word: 'reminisce', weight: 3},
    {word: 'nostalgia', weight: 3},
    {word: 'flashback', weight: 3},
    {word: 'old', weight: 1},
    {word: 'history', weight: 2},
    {word: 'forgotten', weight: 2},
    {word: 'time', weight: 1},
    {word: 'reflection', weight: 2},
    {word: 'dream', weight: 2},
    {word: 'imprint', weight: 3},
    {word: 'loss', weight: 2},
    
    // More specific (4-7)
    {word: 'repressed-memory', weight: 5},
    {word: 'suppressed-memory', weight: 5},
    {word: 'false-memory', weight: 6},
    {word: 'recovered-memory', weight: 6},
    {word: 'traumatic-memory', weight: 5},
    {word: 'muscle-memory', weight: 4},
    {word: 'procedural-memory', weight: 5},
    {word: 'episodic-memory', weight: 5},
    {word: 'semantic-memory', weight: 5},
    {word: 'working-memory', weight: 5},
    {word: 'long-term-memory', weight: 4},
    {word: 'short-term-memory', weight: 4},
    {word: 'collective-memory', weight: 5},
    {word: 'cultural-memory', weight: 5},
    {word: 'childhood-amnesia', weight: 6},
    {word: 'memory-palace', weight: 5},
    {word: 'mnemonic', weight: 5},
    {word: 'déjà-vu', weight: 4},
    {word: 'jamais-vu', weight: 6},
    
    // Niche/specific (7-10)
    {word: 'consolidation', weight: 7},
    {word: 'reconsolidation', weight: 8},
    {word: 'engram', weight: 8},
    {word: 'flashbulb-memory', weight: 7},
    {word: 'proustian-memory', weight: 8},
    {word: 'involuntary-memory', weight: 7},
    {word: 'prospective-memory', weight: 7},
    {word: 'retrograde-amnesia', weight: 7},
    {word: 'anterograde-amnesia', weight: 7},
    {word: 'dissociative-amnesia', weight: 7},
    {word: 'cryptomnesia', weight: 8},
    {word: 'confabulation', weight: 7},
    {word: 'hypermnesia', weight: 8},
    {word: 'eidetic-memory', weight: 7},
    {word: 'mnemonist', weight: 8},
    {word: 'reminiscence-bump', weight: 8},
    {word: 'reminiscence-therapy', weight: 7},
    {word: 'neuroplasticity', weight: 6},
    {word: 'memory-bias', weight: 6},
    {word: 'rosy-retrospection', weight: 7}
  ],

  'Spirituality': [
    // Generic (1-3)
    {word: 'spirit', weight: 1},
    {word: 'god', weight: 1},
    {word: 'faith', weight: 1},
    {word: 'prayer', weight: 2},
    {word: 'divine', weight: 2},
    {word: 'heaven', weight: 2},
    {word: 'sacred', weight: 2},
    {word: 'worship', weight: 2},
    {word: 'soul', weight: 2},
    {word: 'meditate', weight: 2},
    {word: 'holy', weight: 2},
    {word: 'bless', weight: 2},
    {word: 'angel', weight: 2},
    {word: 'miracle', weight: 3},
    {word: 'transcendence', weight: 3},
    {word: 'atonement', weight: 3},
    
    // More specific (4-7)
    {word: 'mindfulness', weight: 4},
    {word: 'enlightenment', weight: 4},
    {word: 'awakening', weight: 4},
    {word: 'consciousness', weight: 4},
    {word: 'higher-self', weight: 4},
    {word: 'inner-peace', weight: 4},
    {word: 'spiritual-journey', weight: 4},
    {word: 'chakras', weight: 5},
    {word: 'aura', weight: 5},
    {word: 'karma', weight: 4},
    {word: 'dharma', weight: 5},
    {word: 'reincarnation', weight: 4},
    {word: 'nirvana', weight: 5},
    {word: 'samsara', weight: 6},
    {word: 'manifestation', weight: 5},
    {word: 'law-of-attraction', weight: 5},
    {word: 'energy-healing', weight: 5},
    {word: 'crystal-healing', weight: 6},
    {word: 'shamanism', weight: 5},
    {word: 'mysticism', weight: 5},
    
    // Niche/specific (7-10)
    {word: 'non-dual-awareness', weight: 8},
    {word: 'advaita-vedanta', weight: 9},
    {word: 'samadhi', weight: 8},
    {word: 'satori', weight: 8},
    {word: 'kensho', weight: 9},
    {word: 'moksha', weight: 8},
    {word: 'bodhi', weight: 8},
    {word: 'prajna', weight: 9},
    {word: 'vipassana', weight: 8},
    {word: 'dzogchen', weight: 9},
    {word: 'mahamudra', weight: 9},
    {word: 'kundalini', weight: 7},
    {word: 'prana', weight: 7},
    {word: 'qi', weight: 6},
    {word: 'meridians', weight: 6},
    {word: 'astral-projection', weight: 7},
    {word: 'channeling', weight: 7},
    {word: 'medium', weight: 6},
    {word: 'clairvoyance', weight: 7},
    {word: 'telepathy', weight: 6},
    {word: 'synchronicity', weight: 6},
    {word: 'akashic-records', weight: 8},
    {word: 'light-worker', weight: 7},
    {word: 'indigo-children', weight: 8}
  ],

  'Faith': [
    // Generic (1-3)
    {word: 'faith', weight: 1},
    {word: 'belief', weight: 1},
    {word: 'trust', weight: 1},
    {word: 'hope', weight: 1},
    {word: 'devotion', weight: 2},
    {word: 'confidence', weight: 2},
    {word: 'certainty', weight: 2},
    {word: 'religion', weight: 2},
    {word: 'spirit', weight: 2},
    
    // More specific (4-7)
    {word: 'blind-faith', weight: 4},
    {word: 'leap-of-faith', weight: 4},
    {word: 'crisis-of-faith', weight: 5},
    {word: 'loss-of-faith', weight: 5},
    {word: 'religious-faith', weight: 4},
    {word: 'spiritual-faith', weight: 4},
    {word: 'faith-community', weight: 4},
    {word: 'faith-based', weight: 4},
    {word: 'interfaith', weight: 5},
    {word: 'secular-faith', weight: 5},
    {word: 'humanistic-faith', weight: 6},
    {word: 'rational-faith', weight: 5},
    {word: 'mystical-faith', weight: 6},
    {word: 'childlike-faith', weight: 5},
    {word: 'mature-faith', weight: 5},
    {word: 'questioning-faith', weight: 5},
    
    // Niche/specific (7-10)
    {word: 'fideism', weight: 8},
    {word: 'evidentialism', weight: 8},
    {word: 'reformed-epistemology', weight: 9},
    {word: 'religious-epistemology', weight: 8},
    {word: 'kierkegaardian-faith', weight: 9},
    {word: 'pascals-wager', weight: 8},
    {word: 'will-to-believe', weight: 8},
    {word: 'credal-assent', weight: 9},
    {word: 'fiducia', weight: 9},
    {word: 'notitia', weight: 9},
    {word: 'assensus', weight: 9},
    {word: 'faith-seeking-understanding', weight: 8},
    {word: 'credo-ut-intelligam', weight: 9},
    {word: 'fides-quaerens-intellectum', weight: 9}
  ],

  'Ego': [
    // Generic (1-3)
    {word: 'ego', weight: 1},
    {word: 'pride', weight: 2},
    {word: 'selfish', weight: 2},
    {word: 'arrogance', weight: 3},
    {word: 'vain', weight: 3},
    {word: 'narcissism', weight: 3},
    {word: 'self', weight: 1},
    {word: 'identity', weight: 2},
    {word: 'image', weight: 2},
    
    // More specific (4-7)
    {word: 'ego-death', weight: 5},
    {word: 'ego-dissolution', weight: 6},
    {word: 'false-ego', weight: 5},
    {word: 'healthy-ego', weight: 5},
    {word: 'ego-strength', weight: 5},
    {word: 'ego-defense', weight: 5},
    {word: 'superego', weight: 4},
    {word: 'id', weight: 4},
    {word: 'ego-ideal', weight: 6},
    {word: 'narcissistic-supply', weight: 6},
    {word: 'grandiose-self', weight: 6},
    {word: 'fragile-ego', weight: 5},
    {word: 'wounded-ego', weight: 5},
    {word: 'ego-trip', weight: 4},
    {word: 'ego-boost', weight: 4},
    {word: 'ego-bruising', weight: 5},
    
    // Niche/specific (7-10)
    {word: 'ego-syntonic', weight: 8},
    {word: 'ego-dystonic', weight: 8},
    {word: 'primary-narcissism', weight: 7},
    {word: 'secondary-narcissism', weight: 7},
    {word: 'pathological-narcissism', weight: 6},
    {word: 'malignant-narcissism', weight: 7},
    {word: 'covert-narcissism', weight: 6},
    {word: 'overt-narcissism', weight: 6},
    {word: 'vulnerable-narcissism', weight: 7},
    {word: 'grandiose-narcissism', weight: 7},
    {word: 'narcissistic-rage', weight: 6},
    {word: 'narcissistic-injury', weight: 7},
    {word: 'false-self', weight: 6},
    {word: 'true-self', weight: 6},
    {word: 'mirroring', weight: 6},
    {word: 'idealizing', weight: 6},
    {word: 'twinship', weight: 8},
    {word: 'selfobject', weight: 8}
  ],

  'Reflection': [
    // Generic (1-3)
    {word: 'reflection', weight: 1},
    {word: 'think', weight: 1},
    {word: 'ponder', weight: 2},
    {word: 'consider', weight: 2},
    {word: 'meditate', weight: 2},
    {word: 'introspect', weight: 3},
    {word: 'analyse', weight: 2},
    {word: 'question', weight: 2},
    {word: 'philosophy', weight: 2},
    
    // More specific (4-7)
    {word: 'self-reflection', weight: 4},
    {word: 'deep-thought', weight: 4},
    {word: 'contemplation', weight: 4},
    {word: 'introspection', weight: 4},
    {word: 'self-examination', weight: 5},
    {word: 'mindfulness', weight: 4},
    {word: 'mindful-awareness', weight: 5},
    {word: 'conscious-reflection', weight: 5},
    {word: 'critical-thinking', weight: 4},
    {word: 'philosophical-inquiry', weight: 5},
    {word: 'existential-questioning', weight: 6},
    {word: 'soul-searching', weight: 5},
    {word: 'inner-dialogue', weight: 5},
    {word: 'stream-of-consciousness', weight: 5},
    {word: 'reflective-practice', weight: 5},
    {word: 'journaling', weight: 4},
    
    // Niche/specific (7-10)
    {word: 'metacognition', weight: 7},
    {word: 'metacognitive-awareness', weight: 8},
    {word: 'phenomenological-reflection', weight: 9},
    {word: 'hermeneutical-reflection', weight: 9},
    {word: 'dialectical-thinking', weight: 7},
    {word: 'reflective-equilibrium', weight: 8},
    {word: 'transcendental-reflection', weight: 9},
    {word: 'epoché', weight: 9},
    {word: 'bracketing', weight: 8},
    {word: 'phenomenological-reduction', weight: 9},
    {word: 'eidetic-reduction', weight: 9},
    {word: 'intentionality', weight: 8},
    {word: 'noesis', weight: 9},
    {word: 'noema', weight: 9},
    {word: 'reflective-judgment', weight: 8}
  ],

  'Time': [
    // Generic (1-3)
    {word: 'time', weight: 1},
    {word: 'years', weight: 1},
    {word: 'age', weight: 1},
    {word: 'clock', weight: 2},
    {word: 'hour', weight: 1},
    {word: 'moment', weight: 1},
    {word: 'past', weight: 1},
    {word: 'future', weight: 1},
    {word: 'present', weight: 1},
    {word: 'eternity', weight: 3},
    {word: 'day', weight: 1},
    {word: 'night', weight: 1},
    {word: 'season', weight: 2},
    {word: 'second', weight: 1},
    {word: 'minute', weight: 1},
    {word: 'decade', weight: 2},
    {word: 'millennium', weight: 3},
    {word: 'timeline', weight: 2},
    {word: 'wait', weight: 1},
    
    // More specific (4-7)
    {word: 'chronology', weight: 4},
    {word: 'temporal', weight: 4},
    {word: 'duration', weight: 4},
    {word: 'sequence', weight: 3},
    {word: 'simultaneity', weight: 5},
    {word: 'synchronicity', weight: 5},
    {word: 'time-perception', weight: 5},
    {word: 'time-dilation', weight: 6},
    {word: 'relativity', weight: 5},
    {word: 'spacetime', weight: 6},
    {word: 'temporal-lobe', weight: 6},
    {word: 'circadian-rhythm', weight: 5},
    {word: 'biorhythm', weight: 5},
    {word: 'time-management', weight: 4},
    {word: 'procrastination', weight: 4},
    {word: 'time-anxiety', weight: 5},
    {word: 'time-blindness', weight: 6},
    
    // Niche/specific (7-10)
    {word: 'chronesthesia', weight: 8},
    {word: 'temporal-displacement', weight: 7},
    {word: 'chronostasis', weight: 8},
    {word: 'temporal-illusion', weight: 7},
    {word: 'time-agnosia', weight: 8},
    {word: 'chronotope', weight: 8},
    {word: 'kairos', weight: 7},
    {word: 'chronos', weight: 7},
    {word: 'aion', weight: 8},
    {word: 'durée', weight: 8},
    {word: 'lived-time', weight: 7},
    {word: 'phenomenological-time', weight: 9},
    {word: 'experienced-time', weight: 6},
    {word: 'clock-time', weight: 5},
    {word: 'psychological-time', weight: 6},
    {word: 'subjective-time', weight: 6},
    {word: 'objective-time', weight: 6},
    {word: 'deep-time', weight: 7},
    {word: 'geological-time', weight: 6}
  ],

  'Change': [
    // Generic (1-3)
    {word: 'change', weight: 1},
    {word: 'transform', weight: 2},
    {word: 'shift', weight: 2},
    {word: 'alter', weight: 2},
    {word: 'evolve', weight: 2},
    {word: 'adapt', weight: 2},
    {word: 'grow', weight: 1},
    {word: 'develop', weight: 2},
    {word: 'metamorphosis', weight: 3},
    {word: 'mutation', weight: 3},
    {word: 'transition', weight: 2},
    {word: 'renewal', weight: 3},
    {word: 'progress', weight: 2},
    
    // More specific (4-7)
    {word: 'personal-transformation', weight: 4},
    {word: 'paradigm-shift', weight: 5},
    {word: 'behavioral-change', weight: 4},
    {word: 'systemic-change', weight: 5},
    {word: 'incremental-change', weight: 5},
    {word: 'radical-change', weight: 4},
    {word: 'evolutionary-change', weight: 5},
    {word: 'revolutionary-change', weight: 5},
    {word: 'change-management', weight: 5},
    {word: 'resistance-to-change', weight: 5},
    {word: 'change-agent', weight: 5},
    {word: 'transformational-leadership', weight: 6},
    {word: 'organizational-change', weight: 5},
    {word: 'cultural-change', weight: 5},
    {word: 'social-change', weight: 4},
    {word: 'climate-change', weight: 4},
    
    // Niche/specific (7-10)
    {word: 'transtheoretical-model', weight: 8},
    {word: 'stages-of-change', weight: 7},
    {word: 'precontemplation', weight: 8},
    {word: 'contemplation', weight: 6},
    {word: 'preparation', weight: 5},
    {word: 'action', weight: 4},
    {word: 'maintenance', weight: 5},
    {word: 'relapse', weight: 5},
    {word: 'change-blindness', weight: 7},
    {word: 'discontinuous-change', weight: 7},
    {word: 'punctuated-equilibrium', weight: 8},
    {word: 'emergence', weight: 6},
    {word: 'phase-transition', weight: 7},
    {word: 'bifurcation', weight: 8},
    {word: 'chaos-theory', weight: 7},
    {word: 'butterfly-effect', weight: 6},
    {word: 'tipping-point', weight: 6},
    {word: 'threshold', weight: 5}
  ],

  'Aging': [
    // Generic (1-3)
    {word: 'aging', weight: 1},
    {word: 'old', weight: 1},
    {word: 'senior', weight: 2},
    {word: 'youth', weight: 1},
    {word: 'wrinkles', weight: 2},
    {word: 'time', weight: 1},
    {word: 'decay', weight: 3},
    {word: 'experience', weight: 2},
    {word: 'wisdom', weight: 2},
    {word: 'frail', weight: 3},
    {word: 'elderly', weight: 2},
    
    // More specific (4-7)
    {word: 'graceful-aging', weight: 4},
    {word: 'healthy-aging', weight: 4},
    {word: 'successful-aging', weight: 5},
    {word: 'active-aging', weight: 4},
    {word: 'cognitive-decline', weight: 5},
    {word: 'age-related-changes', weight: 4},
    {word: 'longevity', weight: 4},
    {word: 'life-expectancy', weight: 4},
    {word: 'generational-differences', weight: 5},
    {word: 'intergenerational-relationships', weight: 6},
    {word: 'ageism', weight: 5},
    {word: 'age-discrimination', weight: 5},
    {word: 'retirement', weight: 3},
    {word: 'pension', weight: 3},
    {word: 'golden-years', weight: 4},
    {word: 'senior-moments', weight: 4},
    
    // Niche/specific (7-10)
    {word: 'chronological-aging', weight: 6},
    {word: 'biological-aging', weight: 6},
    {word: 'psychological-aging', weight: 7},
    {word: 'social-aging', weight: 6},
    {word: 'cellular-senescence', weight: 8},
    {word: 'telomere-shortening', weight: 8},
    {word: 'oxidative-stress', weight: 7},
    {word: 'inflammaging', weight: 8},
    {word: 'gerontology', weight: 7},
    {word: 'geriatrics', weight: 6},
    {word: 'geroscience', weight: 8},
    {word: 'anti-aging', weight: 5},
    {word: 'life-extension', weight: 6},
    {word: 'compression-of-morbidity', weight: 8},
    {word: 'rectangularization', weight: 9},
    {word: 'hayflick-limit', weight: 9},
    {word: 'progeria', weight: 7},
    {word: 'werner-syndrome', weight: 8}
  ],

  'Death': [
    // Generic (1-3)
    {word: 'death', weight: 1},
    {word: 'dead', weight: 1},
    {word: 'dying', weight: 2},
    {word: 'funeral', weight: 2},
    {word: 'grave', weight: 2},
    {word: 'cemetery', weight: 2},
    {word: 'loss', weight: 2},
    {word: 'mortality', weight: 3},
    {word: 'expire', weight: 3},
    {word: 'last breath', weight: 3},
    {word: 'ashes', weight: 2},
    {word: 'end', weight: 1},
    {word: 'departure', weight: 3},
    {word: 'perish', weight: 3},
    {word: 'darkness', weight: 2},
    {word: 'sorrow', weight: 2},
    {word: 'afterlife', weight: 3},
    
    // More specific (4-7)
    {word: 'terminal-illness', weight: 4},
    {word: 'palliative-care', weight: 5},
    {word: 'hospice', weight: 5},
    {word: 'end-of-life', weight: 4},
    {word: 'dying-process', weight: 5},
    {word: 'death-anxiety', weight: 5},
    {word: 'fear-of-death', weight: 4},
    {word: 'near-death-experience', weight: 5},
    {word: 'clinical-death', weight: 5},
    {word: 'brain-death', weight: 5},
    {word: 'cardiac-death', weight: 5},
    {word: 'sudden-death', weight: 4},
    {word: 'peaceful-death', weight: 4},
    {word: 'good-death', weight: 5},
    {word: 'dignified-death', weight: 5},
    {word: 'assisted-dying', weight: 6},
    {word: 'euthanasia', weight: 6},
    {word: 'suicide', weight: 4},
    {word: 'homicide', weight: 4},
    
    // Niche/specific (7-10)
    {word: 'thanatology', weight: 8},
    {word: 'thanatophobia', weight: 7},
    {word: 'death-studies', weight: 7},
    {word: 'mortality-salience', weight: 8},
    {word: 'terror-management-theory', weight: 8},
    {word: 'death-denial', weight: 7},
    {word: 'symbolic-immortality', weight: 8},
    {word: 'immortality-projects', weight: 8},
    {word: 'death-drive', weight: 7},
    {word: 'thanatos', weight: 7},
    {word: 'eros', weight: 6},
    {word: 'memento-mori', weight: 7},
    {word: 'danse-macabre', weight: 8},
    {word: 'ars-moriendi', weight: 9},
    {word: 'viaticum', weight: 9},
    {word: 'extreme-unction', weight: 8},
    {word: 'wake', weight: 4},
    {word: 'viewing', weight: 4},
    {word: 'embalming', weight: 5},
    {word: 'cremation', weight: 4},
    {word: 'burial', weight: 3},
    {word: 'interment', weight: 5}
  ],

  'Rebirth': [
    // Generic (1-3)
    {word: 'rebirth', weight: 1},
    {word: 'renewal', weight: 2},
    {word: 'regeneration', weight: 3},
    {word: 'resurrection', weight: 3},
    {word: 'beginning', weight: 1},
    {word: 'new life', weight: 2},
    {word: 'spring', weight: 2},
    {word: 'awakening', weight: 2},
    {word: 'revival', weight: 3},
    
    // More specific (4-7)
    {word: 'spiritual-rebirth', weight: 4},
    {word: 'born-again', weight: 4},
    {word: 'second-chance', weight: 4},
    {word: 'fresh-start', weight: 3},
    {word: 'new-beginning', weight: 3},
    {word: 'reinvention', weight: 4},
    {word: 'transformation', weight: 3},
    {word: 'metamorphosis', weight: 4},
    {word: 'phoenix-rising', weight: 5},
    {word: 'rising-from-ashes', weight: 5},
    {word: 'comeback', weight: 3},
    {word: 'resurgence', weight: 4},
    {word: 'renaissance', weight: 4},
    {word: 'revitalization', weight: 5},
    {word: 'rejuvenation', weight: 4},
    {word: 'restoration', weight: 4},
    
    // Niche/specific (7-10)
    {word: 'palingenesis', weight: 9},
    {word: 'metempsychosis', weight: 9},
    {word: 'transmigration', weight: 8},
    {word: 'samsara', weight: 7},
    {word: 'reincarnation', weight: 6},
    {word: 'avatar', weight: 6},
    {word: 'incarnation', weight: 6},
    {word: 'apotheosis', weight: 8},
    {word: 'theosis', weight: 9},
    {word: 'anastasis', weight: 9},
    {word: 'eschatological-hope', weight: 9},
    {word: 'eternal-return', weight: 8},
    {word: 'cyclical-time', weight: 7},
    {word: 'ouroboros', weight: 8},
    {word: 'wheel-of-life', weight: 7},
    {word: 'bhavachakra', weight: 9}
  ]
};